# Generated by Django 5.1.4 on 2025-01-06 16:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='register',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('register_FullName', models.CharField(max_length=50)),
                ('register_Email', models.EmailField(max_length=50)),
                ('register_PhoneNumber', models.TextField(max_length=50)),
                ('register_DateOfBirth', models.TextField(max_length=10)),
                ('register_Gender', models.CharField(max_length=10)),
                ('register_Password', models.TextField(max_length=12)),
                ('register_ReEnterPassword', models.TextField(max_length=12)),
            ],
        ),
    ]
