# Generated by Django 5.1.4 on 2025-01-23 05:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0002_contact'),
    ]

    operations = [
        migrations.DeleteModel(
            name='contact',
        ),
    ]
