# Generated by Django 5.1.4 on 2025-01-23 06:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0005_admission_alter_contact_contact_message_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='admission',
            new_name='admissions',
        ),
    ]
