# Generated by Django 5.1.4 on 2025-01-27 04:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0006_rename_admission_admissions'),
    ]

    operations = [
        migrations.CreateModel(
            name='course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course_python', models.CharField(max_length=20)),
                ('course_java', models.CharField(max_length=20)),
                ('course_rust', models.CharField(max_length=20)),
                ('course_swift', models.CharField(max_length=20)),
                ('course_html', models.CharField(max_length=20)),
                ('course_php', models.CharField(max_length=20)),
            ],
        ),
    ]
