# Generated by Django 5.1.4 on 2025-01-28 04:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0007_course'),
    ]

    operations = [
        migrations.CreateModel(
            name='course_data',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course_name', models.CharField(max_length=20)),
                ('course_fees', models.CharField(max_length=10)),
                ('course_student', models.CharField(max_length=10)),
            ],
        ),
        migrations.DeleteModel(
            name='course',
        ),
    ]
