# Generated by Django 5.1.4 on 2025-01-28 15:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0008_course_data_delete_course'),
    ]

    operations = [
        migrations.AddField(
            model_name='course_data',
            name='course_img',
            field=models.URLField(default=500, max_length=500),
            preserve_default=False,
        ),
    ]
