# Generated by Django 5.1.4 on 2025-01-28 16:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0009_course_data_course_img'),
    ]

    operations = [
        migrations.DeleteModel(
            name='course_data',
        ),
    ]
