# Generated by Django 5.1.4 on 2025-01-29 07:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0012_teacher'),
    ]

    operations = [
        migrations.AddField(
            model_name='course_data',
            name='course_price',
            field=models.CharField(default=10, max_length=10),
            preserve_default=False,
        ),
    ]
