# Generated by Django 5.1.4 on 2025-01-29 08:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0013_course_data_course_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course_data',
            name='course_student',
            field=models.CharField(max_length=50),
        ),
    ]
