# Generated by Django 5.1.4 on 2025-01-29 12:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0014_alter_course_data_course_student'),
    ]

    operations = [
        migrations.CreateModel(
            name='gallery_data',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gimg', models.URLField(max_length=500)),
            ],
        ),
    ]
