# Generated by Django 5.1.4 on 2025-01-30 04:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0015_gallery_data'),
    ]

    operations = [
        migrations.CreateModel(
            name='placement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stdimg', models.URLField(max_length=500)),
                ('stdname', models.CharField(max_length=50)),
                ('stdcourse', models.CharField(max_length=20)),
                ('stdlpa', models.CharField(max_length=10)),
            ],
        ),
    ]
