# Generated by Django 5.1.4 on 2025-01-30 05:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0016_placement'),
    ]

    operations = [
        migrations.CreateModel(
            name='courseimg',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cimg', models.URLField(max_length=500)),
                ('cname', models.CharField(max_length=50)),
            ],
        ),
    ]
