# Generated by Django 5.1.4 on 2025-01-30 11:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0017_courseimg'),
    ]

    operations = [
        migrations.AddField(
            model_name='teacher',
            name='tprofile',
            field=models.URLField(default=10),
            preserve_default=False,
        ),
    ]
