# Generated by Django 5.1.4 on 2025-01-30 12:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0019_course_data_course_about'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course_data',
            name='course_about',
            field=models.CharField(max_length=500),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='tprofile',
            field=models.URLField(max_length=500),
        ),
    ]
