# Generated by Django 5.1.4 on 2025-01-30 16:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0021_material'),
    ]

    operations = [
        migrations.AddField(
            model_name='material',
            name='pdf',
            field=models.URLField(default=10, max_length=500),
            preserve_default=False,
        ),
    ]
