# Generated by Django 5.1.4 on 2025-02-01 05:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0022_material_pdf'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='material',
            name='pdf',
        ),
        migrations.RemoveField(
            model_name='material',
            name='sub1',
        ),
        migrations.RemoveField(
            model_name='material',
            name='sub2',
        ),
        migrations.RemoveField(
            model_name='material',
            name='sub3',
        ),
        migrations.RemoveField(
            model_name='material',
            name='sub4',
        ),
        migrations.RemoveField(
            model_name='material',
            name='sub5',
        ),
        migrations.RemoveField(
            model_name='material',
            name='sub6',
        ),
        migrations.AlterField(
            model_name='material',
            name='mname',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='material',
            name='mpdf',
            field=models.URLField(max_length=500),
        ),
    ]
