# Generated by Django 5.1.4 on 2025-02-01 05:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0024_material_mpdfname'),
    ]

    operations = [
        migrations.CreateModel(
            name='assignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('aname', models.CharField(max_length=50)),
                ('apdf', models.URLField(max_length=500)),
                ('apdfname', models.CharField(max_length=50)),
            ],
        ),
    ]
