# Generated by Django 4.2.19 on 2025-03-11 18:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0025_assignment'),
    ]

    operations = [
        migrations.AddField(
            model_name='register',
            name='register_Username',
            field=models.CharField(default=1, max_length=50),
            preserve_default=False,
        ),
    ]
