# Generated by Django 4.2.19 on 2025-03-17 20:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0026_register_register_username'),
    ]

    operations = [
        migrations.AlterField(
            model_name='register',
            name='register_Password',
            field=models.CharField(max_length=12),
        ),
        migrations.AlterField(
            model_name='register',
            name='register_ReEnterPassword',
            field=models.CharField(max_length=12),
        ),
    ]
