# Generated by Django 4.2.19 on 2025-03-18 17:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0027_alter_register_register_password_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='register',
            name='register_Password',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='register',
            name='register_ReEnterPassword',
            field=models.CharField(max_length=50),
        ),
    ]
