# Generated by Django 4.2.19 on 2025-03-18 20:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0028_alter_register_register_password_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='register',
            name='register_Username',
            field=models.CharField(max_length=50, unique=True),
        ),
    ]
