# Generated by Django 4.2.19 on 2025-03-18 20:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0029_alter_register_register_username'),
    ]

    operations = [
        migrations.AlterField(
            model_name='register',
            name='register_Username',
            field=models.CharField(max_length=50),
        ),
    ]
