# Generated by Django 4.2.19 on 2025-03-18 22:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0030_alter_register_register_username'),
    ]

    operations = [
        migrations.AlterField(
            model_name='register',
            name='id',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
    ]
