# Generated by Django 4.2.19 on 2025-03-18 22:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0031_alter_register_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='register',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='register',
            name='register_DateOfBirth',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='register',
            name='register_Email',
            field=models.EmailField(max_length=254),
        ),
        migrations.AlterField(
            model_name='register',
            name='register_FullName',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='register',
            name='register_Password',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='register',
            name='register_PhoneNumber',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='register',
            name='register_ReEnterPassword',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='register',
            name='register_Username',
            field=models.CharField(max_length=150),
        ),
    ]
