# Generated by Django 4.2.19 on 2025-03-18 23:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0033_alter_register_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='register',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
