# Generated by Django 4.2.19 on 2025-03-18 23:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0034_alter_register_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='register',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
