# Generated by Django 4.2.19 on 2025-03-20 18:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0035_alter_register_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='register',
            name='register_PhoneNumber',
            field=models.CharField(max_length=10),
        ),
    ]
