# Generated by Django 4.2.19 on 2025-03-20 18:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0036_alter_register_register_phonenumber'),
    ]

    operations = [
        migrations.AlterField(
            model_name='register',
            name='register_PhoneNumber',
            field=models.CharField(max_length=20),
        ),
    ]
